branches:
  only:
    - /\d+\.\d+\.\d+/
language: python
python: "3.6"
install: true
script: echo "Nothing to build"
before_deploy:
  - pip install -q git+https://github.com/romanvm/kodi-addon-submitter.git
  - submit-addon -z service.subtitles.rvm.addic7ed
  - export RELEASE_ZIP=$(ls *.zip)
deploy:
  - provider: releases
    api_key: $GH_TOKEN
    file_glob: true
    file: $RELEASE_ZIP
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: submit-addon -r repo-scripts -b krypton --pull-request service.subtitles.rvm.addic7ded
    on:
      tags: true
notifications:
  email: false
